### ISSUE TITLE
Cannot login - Debian 13

### ISSUE THREAD

**Issue by ArchiMark** [lrussell887/Debian-for-WM8505-Netbooks#8]
Don't recall that install asked me to set a username. Just asked me to set a password.

Don't see on the ReadMe info regarding what name to use to login the first time.

Please advise.

**Comment by lrussell887** [comment]
Only a root password is set during setup, so please sign in with the username `root`. You'll have to add a normal user manually with `adduser username`. Please let me know if you run into any issues.

**Comment by ArchiMark** [comment]
Thank you for your quick reply and input.

However, I have tried doing what you say, many times, and every time I get message, login incorrect.

Also, get message about bad frame size. Could this relate to problem logging in?

Thanks,

Mark

**Comment by lrussell887** [comment]
I've not seen the `bad frame size` message but I can only surmise it has something to do with ethernet perhaps? Either way that wouldn't affect logging in. If you could get me an image of the error though it would be appreciated.

While I haven't extensively tested the Debian 13 build, I haven't run into any login issues in my testing beyond it timing out during first boot which I addressed before release. Is it possible you had caps lock turned on or otherwise mistyped the password twice when setting it? I'd recommend re-flashing your SD card with a fresh image and trying the setup process again.

**Comment by ArchiMark** [comment]
Thanks for your input and suggestion.

Tried entering password in caps, but still no go….

Will try reinstalling fresh as you suggest…..

Please see attached image of error.

￼

**Comment by ArchiMark** [comment]
Tried downloading file (3rd time….) and reflashing SD card.

Unfortunately, I still have same issue…..

Enter password and then after a minute I see on screen as if it worked (also shows info about debian….) and then after a short bit, the screen goes black and just see a blinking white dash at top left of screen. Then after a short bit, I get back to login prompt.

???

**Comment by lrussell887** [comment]
That may be getty's 60 second timeout causing problems during first boot because the netbook is so slow. I tried to get systemd to wait for the most intensive services but for whatever reason in your case it must not be enough. Try leaving it at the login screen for a few minutes to let things settle and it hopefully will let you in afterwards. The only other suggestion I would have is to try an external keyboard if it tells you your password is incorrect.

**Comment by ArchiMark** [comment]
Think you were right about the timeout…..

I tried waiting a bit to try and login……

Took a few tries, but then it finally worked and I was logged in!!!!

:-)

Now onto to install WM and some apps……

:-)


Thanks again for all your help and support!

And thanks for supporting Debian on the Sylania!

**Comment by ArchiMark** [comment]
Well, I celebrated too soon….

I installed a bunch of apps, including jwm and lightdm, went OK.

Then I rebooted and now I can’t login. Tried many times…

Tried rebooting again and same thing, tried logging in many times.

After the third reboot, I gave up.

See attached photos. I was getting message about memory pressure issue too.

And see message about adduser.

Unless you have an idea, I’ll wait until your next release and try again.

￼
￼
￼

￼
￼

**Comment by lrussell887** [comment]
I'm sorry none of your attached pictures are appearing. Memory pressure is just journald flushing its caches and should be benign. Clearly Debian 13 will need some additional work to get running well on this hardware. I'd suggest sticking with Debian 12 for now until I have a chance to try to look deeper. I've marked the Debian 13 build as pre-release accordingly.

**Comment by ArchiMark** [comment]
Sorry, for the prior blank message….accidentally hit send…..

Strange about the pictures not showing up….

Thanks, as always, for your responses and help.

Will do as you suggest and stick with 12 for now….

**Comment by RayPS** [comment]
Samething happend to me as well. Newly flashed first boot shows only login wihout asking me anything. Tried to wait for 30 minutes wont do anything. 

Is there a way to temporary bypass first-boot service and set a default user/password at the build time?

**Comment by lrussell887** [comment]
There isn't any tooling right now to bypass setting the password before first boot. It wouldn't make a difference anyway since it's not actually the account creation that's the problem, but the login timing out because the netbook is so slow.

I'll address this with a proper fix as soon as I can. I'm in the process of moving which is why it's taking me a bit. I'll update this issue once I'm able to do so.

**Comment by RayPS** [comment]
I have read the kernel boot process by adding `console=ttyS0,115200n8 earlyprintk` to bootargs.
It stuck here forever, that may explain something.
Let me know if you want me to try something else, hopefully I can provide more useful infomation.

```
WMT # setenv bootargs mem=212M root=/dev/mmcblk0p2 noinitrd rw console=ttyS0,115200n8 earlyprintk rootwait; bootm 0
## Booting image at 00000000 ...
   Image Name:   linux
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    7336404 Bytes =  7 MB
   Load Address: 00008000
   Entry Point:  00008000
   Verifying Checksum ... OK
OK
No initrd
## Transferring control to Linux (at address 00008000) ...

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.12.45-wm8505 (root@z8) (arm-linux-gnueabi-gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #1 Mon Sep  8 08:40:00 HKT 2025
[    0.000000] CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
[    0.000000] CPU: VIVT data cache, VIVT instruction cache
[    0.000000] OF: fdt: Machine model: Wondermedia WM8650-MID Tablet
[    0.000000] printk: legacy bootconsole [earlycon0] enabled
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 32 MiB at 0x0b400000 on node -1
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000000d3fffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000000d3fffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000000d3fffff]
[    0.000000] OF: reserved mem: Reserved memory: No reserved-memory node in the DT
[    0.000000] Kernel command line: mem=212M root=/dev/mmcblk0p2 noinitrd rw console=ttyS0,115200n8 earlyprintk rootwait
[    0.000000] Dentry cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] Inode-cache hash table entries: 16384 (order: 4, 65536 bytes, linear)
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 54272
[    0.000000] allocated 217088 bytes of page_ext
[    0.000000] mem auto-init: stack:all(zero), heap alloc:on, heap free:off
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 35663 entries in 105 pages
[    0.000000] ftrace: allocated 105 pages with 4 groups
[    0.000000] RCU Tasks Rude: Setting shift to 0 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=1.
[    0.000000] RCU Tasks Trace: Setting shift to 0 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=1.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] vt8500-irq: Added interrupt controller
[    0.000000] vt8500-irq: Added interrupt controller
[    0.000000] vt8500-irq: Enabled slave->parent interrupts
[    0.000000] clocksource: vt8500_timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 637086815595 ns
[    0.000000] Console: colour dummy device 80x25
[    0.000000] sched_clock: 32 bits at 100 Hz, resolution 10000000ns, wraps every 21474836475000000ns
[    0.010000] Calibrating delay loop... 348.97 BogoMIPS (lpj=1744896)
[    0.070000] CPU: Testing write buffer coherency: ok
[    0.080000] pid_max: default: 32768 minimum: 301
[    0.090000] LSM: initializing lsm=capability,landlock,lockdown,yama,apparmor,bpf,ipe,ima,evm
[    0.100000] landlock: Up and running.
[    0.110000] Yama: becoming mindful.
[    0.110000] AppArmor: AppArmor initialized
[    0.120000] LSM support for eBPF active
[    0.130000] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.130000] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.160000] Setting up static identity map for 0x100000 - 0x100058
[    0.170000] Memory: 163324K/217088K available (11264K kernel code, 1202K rwdata, 2736K rodata, 1024K init, 363K bss, 19404K reserved, 32768K cma-reserved)
[    0.180000] devtmpfs: initialized
[    0.190000] VFP support v0.3: not present
[    0.190000] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.200000] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.210000] pinctrl core: initialized pinctrl subsystem
[    0.220000] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.250000] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.260000] audit: initializing netlink subsys (disabled)
[    0.260000] thermal_sys: Registered thermal governor 'fair_share'
[    0.260000] thermal_sys: Registered thermal governor 'bang_bang'
[    0.270000] thermal_sys: Registered thermal governor 'step_wise'
[    0.270000] thermal_sys: Registered thermal governor 'user_space'
[    0.280000] No ATAGs?
[    0.300000] kprobes: kprobe jump-optimization is enabled. All kprobes are optimized if possible.
[    0.310000] audit: type=2000 audit(0.260:1): state=initialized audit_enabled=0 res=1
[    0.370000] iommu: Default domain type: Translated
[    0.380000] iommu: DMA domain TLB invalidation policy: strict mode
[    0.380000] usbcore: registered new interface driver usbfs
[    0.390000] usbcore: registered new interface driver hub
[    0.390000] usbcore: registered new device driver usb
[    0.400000] pps_core: LinuxPPS API ver. 1 registered
[    0.400000] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.410000] PTP clock support registered
[    0.450000] clocksource: Switched to clocksource vt8500_timer
[    0.470000] VFS: Disk quotas dquot_6.6.0
[    0.470000] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.480000] AppArmor: AppArmor Filesystem Enabled
[    0.660000] NET: Registered PF_INET protocol family
[    0.670000] IP idents hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.680000] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.690000] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.700000] TCP established hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.710000] TCP bind hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.710000] TCP: Hash tables configured (established 2048 bind 2048)
[    0.720000] MPTCP token hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.730000] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.740000] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.750000] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.750000] NET: Registered PF_XDP protocol family
[    0.850000] Initialise system trusted keyrings
[    0.860000] Key type blacklist registered
[    0.860000] workingset: timestamp_bits=14 max_order=16 bucket_order=2
[    0.870000] zbud: loaded
[    0.890000] fuse: init (API version 7.41)
[    0.900000] integrity: Platform Keyring initialized
[    1.320000] Key type asymmetric registered
[    1.330000] Asymmetric key parser 'x509' registered
[    1.330000] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 248)
[    1.340000] io scheduler mq-deadline registered
[    1.350000] io scheduler kyber registered
[    1.350000] io scheduler bfq registered
[    1.360000] ledtrig-cpu: registered to indicate activity on CPUs
[    1.360000] Enabled support for WMT GE raster acceleration
[    1.400000] Console: switching to colour frame buffer device 100x30
[    1.420000] fb0: wm8505-fb frame buffer at 0xb500000-0xb676fff
[    1.830000] Serial: 8250/16550 driver, 4 ports, IRQ sharing enabled
[    1.850000] d8200000.serial: ttyWMT0 at MMIO 0xd8200000 (irq = 25, base_baud = 923076) is a VT8500 UART-1
[    1.860000] platform-uhci d8007b00.usb: Generic UHCI Host Controller
[    1.870000] ehci-platform d8007900.ehci: EHCI Host Controller
[    1.880000] ehci-platform d8007900.ehci: new USB bus registered, assigned bus number 2
[    1.890000] ehci-platform d8007900.ehci: irq 26, io mem 0xd8007900
[    1.900000] platform-uhci d8007b00.usb: new USB bus registered, assigned bus number 1
[    1.900000] platform-uhci d8007b00.usb: detected 2 ports
[    1.910000] platform-uhci d8007b00.usb: irq 26, io mem 0xd8007b00
[    1.920000] ehci-platform d8007900.ehci: USB 2.0 started, EHCI 1.00
[    1.930000] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.12
[    1.940000] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.940000] usb usb2: Product: EHCI Host Controller
[    1.950000] usb usb2: Manufacturer: Linux 6.12.45-wm8505 ehci_hcd
[    1.950000] usb usb2: SerialNumber: d8007900.ehci
[    1.960000] hub 2-0:1.0: USB hub found
[    1.970000] hub 2-0:1.0: 4 ports detected
[    1.970000] usb usb1: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 6.12
[    1.980000] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.990000] usb usb1: Product: Generic UHCI Host Controller
[    2.000000] usb usb1: Manufacturer: Linux 6.12.45-wm8505 uhci_hcd
[    2.000000] usb usb1: SerialNumber: d8007b00.usb
[    2.010000] hub 1-0:1.0: USB hub found
[    2.010000] hub 1-0:1.0: 2 ports detected
[    2.020000] i8042: i8042_platform_init: no devicetree node found
[    2.030000] mousedev: PS/2 mouse device common for all mice
[    2.040000] vt8500-rtc d8100000.rtc: registered as rtc0
[    2.040000] vt8500-rtc d8100000.rtc: setting system clock to 2000-01-01T00:22:48 UTC (946686168)
[    2.050000] hid: raw HID events driver (C) Jiri Kosina
[    2.060000] usbcore: registered new interface driver usbhid
[    2.070000] usbhid: USB HID core driver
[    2.080000] NET: Registered PF_INET6 protocol family
[    2.100000] Segment Routing with IPv6
[    2.100000] In-situ OAM (IOAM) with IPv6
[    2.110000] mip6: Mobile IPv6
[    2.110000] NET: Registered PF_PACKET protocol family
[    2.120000] wmt-sdhc d800a000.sdhc: WMT SDHC Controller initialized
[    2.130000] mpls_gso: MPLS GSO support
[    2.170000] registered taskstats version 1
[    2.170000] Loading compiled-in X.509 certificates
[    2.200000] Loaded X.509 cert 'Build time autogenerated kernel key: 236c0780879b7359512ddbdf293f7b749b2e1ecb'
[    2.250000] Key type .fscrypt registered
[    2.250000] Key type fscrypt-provisioning registered
[    2.280000] mmc0: new high speed SDHC card at address 0001
[    2.290000] mmcblk0: mmc0:0001 USD 29.8 GiB
[    2.300000] Key type encrypted registered
[    2.310000] AppArmor: AppArmor sha256 policy hashing enabled
[    2.310000] ima: No TPM chip found, activating TPM-bypass!
[    2.320000] ima: Allocated hash algorithm: sha256
[    2.320000] ima: No architecture policies found
[    2.330000] evm: Initialising EVM extended attributes:
[    2.330000] evm: security.selinux (disabled)
[    2.340000] evm: security.SMACK64 (disabled)
[    2.340000] evm: security.SMACK64EXEC (disabled)
[    2.350000] evm: security.SMACK64TRANSMUTE (disabled)
[    2.350000] evm: security.SMACK64MMAP (disabled)
[    2.360000] evm: security.apparmor
[    2.360000] evm: security.ima
[    2.360000] evm: security.capability
[    2.370000] evm: HMAC attrs: 0x1
[    2.380000] clk: Disabling unused clocks
[    2.390000] Warning: unable to open an initial console.
[    2.390000]  mmcblk0: p1 p2
[    2.550000] usb 1-2: new low-speed USB device number 2 using platform-uhci
[    2.810000] usb 1-2: New USB device found, idVendor=04d9, idProduct=2ba0, bcdDevice= 2.52
[    2.820000] usb 1-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[    2.820000] usb 1-2: Product: USB Keyboard
[    2.890000] input: USB Keyboard as /devices/platform/soc/d8007b00.usb/usb1/1-2/1-2:1.0/0003:04D9:2BA0.0001/input/input0
[    2.910000] EXT4-fs (mmcblk0p2): recovery complete
[    2.920000] EXT4-fs (mmcblk0p2): mounted filesystem 04ad0e3c-bddd-4029-ad88-28e429411b20 r/w with ordered data mode. Quota mode: none.
[    2.930000] VFS: Mounted root (ext4 filesystem) on device 179:2.
[    2.950000] Freeing unused kernel image (initmem) memory: 1024K
[    2.960000] Run /sbin/init as init process
[    2.970000] hid-generic 0003:04D9:2BA0.0001: input,hidraw0: USB HID v1.10 Keyboard [USB Keyboard] on usb-d8007b00.usb-2/input0
[    3.040000] usb 2-3: new high-speed USB device number 3 using ehci-platform
[    3.100000] input: USB Keyboard Mouse as /devices/platform/soc/d8007b00.usb/usb1/1-2/1-2:1.1/0003:04D9:2BA0.0002/input/input1
[    3.120000] input: USB Keyboard Consumer Control as /devices/platform/soc/d8007b00.usb/usb1/1-2/1-2:1.1/0003:04D9:2BA0.0002/input/input2
[    3.190000] input: USB Keyboard System Control as /devices/platform/soc/d8007b00.usb/usb1/1-2/1-2:1.1/0003:04D9:2BA0.0002/input/input4
[    3.200000] hid-generic 0003:04D9:2BA0.0002: input,hiddev0,hidraw1: USB HID v1.10 Mouse [USB Keyboard] on usb-d8007b00.usb-2/input1
[    3.240000] usb 2-3: New USB device found, idVendor=05e3, idProduct=0608, bcdDevice=77.63
[    3.250000] usb 2-3: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    3.250000] usb 2-3: Product: USB2.0 Hub
[    3.280000] hub 2-3:1.0: USB hub found
[    3.290000] hub 2-3:1.0: 4 ports detected
[    3.930000] systemd[1]: System time advanced to timestamp on /var/lib/systemd/timesync/clock: Sun 2025-08-10 15:04:31 UTC
[    4.250000] systemd[1]: Inserted module 'autofs4'
[    4.610000] systemd[1]: systemd 257.8-1~deb13u1 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +IPE +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBCRYPTSETUP_PLUGINS +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -BTF -XKBCOMMON -UTMP +SYSVINIT +LIBARCHIVE)
[    4.640000] systemd[1]: Detected architecture arm.
[    4.680000] systemd[1]: Hostname set to <z8>.
[   10.110000] systemd[1]: Queued start job for default target graphical.target.
[   10.330000] systemd[1]: Created slice system-getty.slice - Slice /system/getty.
[   10.360000] systemd[1]: Created slice system-modprobe.slice - Slice /system/modprobe.
[   10.380000] systemd[1]: Created slice user.slice - User and Session Slice.
[   10.390000] systemd[1]: Started systemd-ask-password-console.path - Dispatch Password Requests to Console Directory Watch.
[   10.400000] systemd[1]: Started systemd-ask-password-wall.path - Forward Password Requests to Wall Directory Watch.
[   10.420000] systemd[1]: Set up automount proc-sys-fs-binfmt_misc.automount - Arbitrary Executable File Formats File System Automount Point.
[   10.430000] systemd[1]: Reached target paths.target - Path Units.
[   10.440000] systemd[1]: Reached target remote-fs.target - Remote File Systems.
[   10.450000] systemd[1]: Reached target slices.target - Slice Units.
[   10.500000] systemd[1]: Listening on systemd-creds.socket - Credential Encryption/Decryption.
[   10.510000] systemd[1]: Listening on systemd-initctl.socket - initctl Compatibility Named Pipe.
[   10.530000] systemd[1]: Listening on systemd-journald-audit.socket - Journal Audit Socket.
[   10.540000] systemd[1]: Listening on systemd-journald-dev-log.socket - Journal Socket (/dev/log).
[   10.550000] systemd[1]: Listening on systemd-journald.socket - Journal Sockets.
[   10.570000] systemd[1]: Listening on systemd-networkd.socket - Network Service Netlink Socket.
[   10.580000] systemd[1]: Listening on systemd-udevd-control.socket - udev Control Socket.
[   10.590000] systemd[1]: Listening on systemd-udevd-kernel.socket - udev Kernel Socket.
[   10.610000] systemd[1]: dev-hugepages.mount - Huge Pages File System was skipped because of an unmet condition check (ConditionPathExists=/sys/kernel/mm/hugepages).
[   10.650000] systemd[1]: Mounting dev-mqueue.mount - POSIX Message Queue File System...
[   10.740000] systemd[1]: Mounting run-lock.mount - Legacy Locks Directory /run/lock...
[   10.840000] systemd[1]: Mounting sys-kernel-debug.mount - Kernel Debug File System...
[   10.960000] systemd[1]: Mounting sys-kernel-tracing.mount - Kernel Trace File System...
[   11.160000] systemd[1]: Starting kmod-static-nodes.service - Create List of Static Device Nodes...
[   11.340000] systemd[1]: Starting modprobe@configfs.service - Load Kernel Module configfs...
[   11.550000] systemd[1]: Starting modprobe@drm.service - Load Kernel Module drm...
[   11.790000] systemd[1]: Starting modprobe@efi_pstore.service - Load Kernel Module efi_pstore...
[   12.060000] systemd[1]: Starting modprobe@fuse.service - Load Kernel Module fuse...
[   12.370000] systemd[1]: Starting nftables.service - nftables...
[   12.550000] systemd[1]: systemd-hibernate-clear.service - Clear Stale Hibernate Storage Info was skipped because of an unmet condition check (ConditionPathExists=/sys/firmware/efi/efivars/HibernateLocation-8cf2644b-4b0b-428f-9387-6d876050dc67).
[   13.150000] systemd[1]: Starting systemd-journald.service - Journal Service...
[   13.440000] systemd[1]: Starting systemd-modules-load.service - Load Kernel Modules...
[   13.820000] systemd[1]: Starting systemd-network-generator.service - Generate network units from Kernel command line...
[   14.100000] systemd[1]: Starting systemd-remount-fs.service - Remount Root and Kernel File Systems...
[   14.460000] systemd[1]: Starting systemd-udev-load-credentials.service - Load udev Rules from Credentials...
[   14.840000] systemd[1]: Starting systemd-udev-trigger.service - Coldplug All udev Devices...
[   15.810000] systemd[1]: Mounted dev-mqueue.mount - POSIX Message Queue File System.
[   15.900000] systemd[1]: Mounted run-lock.mount - Legacy Locks Directory /run/lock.
[   15.990000] systemd[1]: Mounted sys-kernel-debug.mount - Kernel Debug File System.
[   16.660000] systemd[1]: Mounted sys-kernel-tracing.mount - Kernel Trace File System.
[   16.730000] systemd[1]: Finished kmod-static-nodes.service - Create List of Static Device Nodes.
[   16.840000] systemd[1]: modprobe@configfs.service: Deactivated successfully.
[   16.890000] systemd[1]: Finished modprobe@configfs.service - Load Kernel Module configfs.
[   17.020000] systemd[1]: modprobe@drm.service: Deactivated successfully.
[   17.200000] systemd[1]: Finished modprobe@drm.service - Load Kernel Module drm.
[   17.540000] systemd[1]: modprobe@efi_pstore.service: Deactivated successfully.
[   17.690000] systemd[1]: Finished modprobe@efi_pstore.service - Load Kernel Module efi_pstore.
[   18.020000] systemd[1]: modprobe@fuse.service: Deactivated successfully.
[   18.070000] systemd[1]: Finished modprobe@fuse.service - Load Kernel Module fuse.
[   18.190000] systemd[1]: Finished nftables.service - nftables.
[   18.270000] systemd[1]: Finished systemd-modules-load.service - Load Kernel Modules.
[   18.350000] systemd[1]: Finished systemd-network-generator.service - Generate network units from Kernel command line.
[   18.470000] systemd[1]: Finished systemd-remount-fs.service - Remount Root and Kernel File Systems.
[   18.550000] systemd[1]: Reached target network-pre.target - Preparation for Network.
[   18.740000] systemd[1]: Activating swap swapfile.swap - /swapfile...
[   18.960000] systemd[1]: Mounting sys-fs-fuse-connections.mount - FUSE Control File System...
[   19.230000] systemd[1]: Mounting sys-kernel-config.mount - Kernel Configuration File System...
[   19.350000] systemd[1]: systemd-hwdb-update.service - Rebuild Hardware Database was skipped because of an unmet condition check (ConditionNeedsUpdate=/etc).
[   19.440000] systemd-journald[92]: Collecting audit messages is enabled.
[   19.560000] systemd[1]: systemd-pstore.service - Platform Persistent Storage Archival was skipped because of an unmet condition check (ConditionDirectoryNotEmpty=/sys/fs/pstore).
[   20.010000] systemd[1]: Starting systemd-random-seed.service - Load/Save OS Random Seed...
[   20.520000] systemd[1]: Starting systemd-sysctl.service - Apply Kernel Variables...
[   21.090000] systemd[1]: Starting systemd-tmpfiles-setup-dev-early.service - Create Static Device Nodes in /dev gracefully...
[   21.450000] systemd[1]: Finished systemd-udev-load-credentials.service - Load udev Rules from Credentials.
[   21.590000] audit: type=1130 audit(1754838289.040:2): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-udev-load-credentials comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   21.910000] Adding 262140k swap on /swapfile.  Priority:-2 extents:3 across:385024k SS
[   22.040000] systemd[1]: Activated swap swapfile.swap - /swapfile.
[   22.160000] systemd[1]: Started systemd-journald.service - Journal Service.
[   22.290000] audit: type=1130 audit(1754838289.730:3): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-journald comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   24.820000] audit: type=1130 audit(1754838292.260:4): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-sysctl comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   25.730000] audit: type=1130 audit(1754838293.170:5): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev-early comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   26.200000] audit: type=1334 audit(1754838293.640:6): prog-id=6 op=LOAD
[   27.830000] random: crng init done
[   28.140000] audit: type=1130 audit(1754838295.580:7): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-random-seed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   28.590000] systemd-journald[92]: Received client request to flush runtime journal.
[   28.620000] systemd-journald[92]: File /var/log/journal/d3eb2119103c4c24bc53a476c01eca54/system.journal corrupted or uncleanly shut down, renaming and replacing.
[   30.420000] audit: type=1130 audit(1754838297.860:8): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup-dev comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   31.090000] audit: type=1334 audit(1754838298.520:9): prog-id=7 op=LOAD
[   31.130000] audit: type=1334 audit(1754838298.580:10): prog-id=8 op=LOAD
[   31.520000] audit: type=1130 audit(1754838298.970:11): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-journal-flush comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   34.980000] audit: type=1130 audit(1754838302.400:12): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   36.760000] audit: type=1130 audit(1754838304.200:13): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-binfmt comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   36.970000] audit: type=1130 audit(1754838304.410:14): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   37.990000] audit: type=1130 audit(1754838305.430:15): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-udevd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   38.140000] audit: type=1334 audit(1754838305.580:16): prog-id=9 op=LOAD
[   39.880000] audit: type=1130 audit(1754838307.320:17): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-udev-trigger comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   40.300000] audit: type=1130 audit(1754838307.740:18): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=cron comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   42.350000] audit: type=1334 audit(1754838309.780:19): prog-id=10 op=LOAD
[   42.480000] audit: type=1334 audit(1754838309.930:20): prog-id=11 op=LOAD
[   42.500000] audit: type=1334 audit(1754838309.940:21): prog-id=12 op=LOAD
[   43.100000] audit: type=1130 audit(1754838310.550:22): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=wlan-gpio comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   46.910000] audit: type=1130 audit(1754838314.290:23): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=ifupdown-pre comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   47.930000] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   48.000000] Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   48.040000] Loaded X.509 cert 'wens: 61c038651aabdcf94bd0ac7ff06c7248db18c600'
[   49.750000] audit: type=1130 audit(1754838317.200:24): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=dbus comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   49.820000] audit: type=1130 audit(1754838317.230:25): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   49.970000] audit: type=1130 audit(1754838317.410:26): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=e2scrub_reap comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   49.990000] audit: type=1131 audit(1754838317.410:27): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=e2scrub_reap comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   50.300000] audit: type=1131 audit(1754838317.730:28): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=wlan-gpio comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
[   55.120000] audit: type=1130 audit(1754838322.560:29): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-logind comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   57.110000] audit: type=1127 audit(1754838324.520:30): pid=179 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg=' comm="wtmpdb" exe="/usr/bin/wtmpdb" hostname=? addr=? terminal=? res=success'
[   57.430000] audit: type=1130 audit(1754838324.860:31): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=wpa_supplicant comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   57.590000] audit: type=1130 audit(1754838325.010:32): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=wtmpdb-update-boot comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   58.140000] audit: type=1130 audit(1754838325.570:33): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-networkd-persistent-storage comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   59.140000] audit: type=1130 audit(1754838326.570:34): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=networking comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   59.660000] audit: type=1334 audit(1754838327.100:35): prog-id=13 op=LOAD
[   59.660000] audit: type=1334 audit(1754838327.100:36): prog-id=14 op=LOAD
[   59.670000] audit: type=1334 audit(1754838327.100:37): prog-id=15 op=LOAD
[   64.370000] audit: type=1130 audit(1754838331.800:38): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   67.030000] audit: type=1130 audit(1754838334.460:39): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=NetworkManager comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   86.170000] audit: type=1130 audit(1754838353.610:40): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=dropbear comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   87.640000] audit: type=1130 audit(1754838355.070:41): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-user-sessions comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   87.880000] audit: type=1130 audit(1754838355.310:42): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=getty@tty1 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   88.210000] audit: type=1130 audit(1754838355.650:43): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   94.700000] audit: type=1131 audit(1754838362.150:44): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   94.760000] audit: type=1334 audit(1754838362.210:45): prog-id=13 op=UNLOAD
[   97.820000] audit: type=1131 audit(1754838365.260:46): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

**Comment by lrussell887** [comment]
Oh my bad I had misunderstood you. I thought you meant you got stuck at the login screen not able to sign in after setting the hostname, timezone, and root password, not that you never even get prompted for first boot setup. The fact that "detected first boot" isn't part of your logs is telling, but that makes me wonder how the hostname "z8" was set. You're certain these kernel logs are from the very first time the image was booted after flashing the SD card?

Oh-- you built your own image now that I look at the kernel version. That's the name of your host system. This all points to something in the build process didn't go quite right, like `config-rootfs.sh` wasn't run properly since it has to for first boot to be triggered. Try the pre-built image under pre-releases and you should see that it prompts you. And what I really need is the full build logs from you. There might be some odd issue with building on Ubuntu 24.04 related to the new use of `mmdebstrap`, or something with your host PC otherwise. I get the feeling the post-hook isn't running in your case. I can try 24.04 myself too once I get things back setup for myself. I had built on a fresh copy of Debian 13 myself. I tried Kubuntu 25.04 but actually need to update the script to handle the host having `/swapfile` mounted causing `mkswap` to fail. That's actually a regression, but probably isn't the issue in this case because that immediately causes the script to exit with a build error. In either case *that* particular issue is a quick fix.

What I've really been wanting to do is containerize the build process anyway to eliminate things like this, but the use of `binfmt-support` to allow the build host to run the ARMv5 binaries requires cooperation from the kernel meaning that something like docker would need root if I remember correctly or the container would really need to be a full-blown virtual machine of its own. Then we wouldn't have to deal with variation from system to system like this. This is starting to turn into a real case of "works on my machine". 😆

EDIT: Actually no, the fact that the swapfile is created at all and mounted on boot means the `config-rootfs.sh` customize-hook was run. Meaning the `rm /etc/machine-id` that actually triggers systemd's first boot logic should have been run inside the chroot. Odd. In any case the build logs would be helpful.

Also, is there any reason you removed `audit=0`? It makes the tty quite noisy without `quiet` and from my understanding is nothing but a performance sink on hardware like this anyway without any real benefit.

**Comment by RayPS** [comment]
That's right! `z8` is the hostname of the my Ubuntu laptop, I made some adjustment according to the readme and build the image for WM8650.
I thought the hostname inherit from the build machine was intended.
I tried to remove machine-id
```shell
sudo rm -f $MNT/etc/machine-id $MNT/var/lib/dbus/machine-id
sudo rm -f $MNT/etc/hostname
```
But that didn't work, except for the hostname is now become 'localhost'
So I think you are right, there is something wrong in the build process.

Finally, I have to chroot to SD card from Ubuntu to create a user manually.
In other words, I confirm it works on WM8650 too, only with firstboot issue.

Here I uploaded the full build logs if you are interested: https://app.warp.dev/block/k5miF2lQ6tCmcJiLtQzlHH



![Image](https://github.com/user-attachments/assets/301227c7-2eeb-409a-a9ee-6d8e9588d6d1)

**Comment by RayPS** [comment]
Update: I can finally see the first boot setup.
For anyone encounter the same issue. This is my bootargs
`setenv bootargs mem=212M root=/dev/mmcblk0p2 noinitrd rw console=ttyWMT0,115200 console=tty1 earlyprintk rootwait audit=0`
I think `console=tty1` is the key!
Without this setting, you will only see a flashing dash and then a login prompt.
With this setting, you can see the full boot logs in colored, and also the first boot setup!

![Image](https://github.com/user-attachments/assets/229f7aec-744f-46e8-9272-8410d0434f44)

**Comment by lrussell887** [comment]
The original login issue should now be resolved by addressing the root cause: yescrypt is simply too demanding on the system, taking several seconds per password and utilizing max CPU. Switched for SHA-512 which is dramatically faster. Since the project has diverged so much since the creation of this issue, please try a new image, and if it persists, I ask that you open a new issue. Thank you.
